description: Volume control input processor for mapping scroll wheel to system volume up/down
compatible: "zmk,input-processor-volume"

include: input-processor.yaml

properties:
  "#input-processor-cells":
    const: 0
