description: Volume control input processor for mapping scroll wheel to system volume up/down
compatible: "zmk,input-processor-volume"

include: base.yaml

properties:
  "#input-processor-cells":
    type: int
    const: 0
